trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscriptionId : "058a36cd-ad87-41c0-8431-a09e57423aee"

steps:
- checkout: self
  persistCredentials: 'true'
- task: PowerShell@2
  displayName: "Install AZ Powershell module"
  inputs:
    targetType: 'inline'
    script: Install-Module -Name Az.Blueprint -Force -Verbose -Scope CurrentUser
    failOnStderr: true
- task: AzurePowerShell@4
  displayName: "Publish all Blueprints"
  inputs:
    azureSubscription: 'ServiceConnection'
    ScriptType: 'FilePath'
    ScriptPath: 'src/main/pwsh/publishBlueprints.ps1'
    ScriptArguments: '-subscriptionId $(subscriptionId)'
    azurePowerShellVersion: 'LatestVersion'
    FailOnStandardError: true